services:
  api:
    build: .
    container_name: server_policard
    ports:
      - "10000:10000"
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
      - ./face_utils.py:/app/face_utils.py
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:123456@postgres:5432/DB_policard

  postgres:
    image: postgres:15
    container_name: postgres_policard
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: DB_policard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d DB_policard"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:
